export const CATEGORIES = [
  { label: 'آبمیوه', icon: 'assets/icons/categories/ابمیوه.svg' },
  { label: 'استیک', icon: 'assets/icons/categories/استیک.svg' },
  { label: 'اسموتی', icon: 'assets/icons/categories/اسموتی.svg' },
  { label: 'اسنک', icon: 'assets/icons/categories/اسنک.svg' },
  { label: 'باگت ساندویچ', icon: 'assets/icons/categories/باگت_ساندویچ.svg' },
  { label: 'برگر', icon: 'assets/icons/categories/برگر.svg' },
  { label: 'بستنی', icon: 'assets/icons/categories/بستنی.svg' },
  { label: 'دمنوش', icon: 'assets/icons/categories/دمنوش.svg' },
  { label: 'دیپ و مزه‌ها', icon: 'assets/icons/categories/دیپ_و_مزه_ها.svg' },
  { label: 'رژیمی', icon: 'assets/icons/categories/رژیمی.svg' },
  { label: 'سالاد', icon: 'assets/icons/categories/سالاد.svg' },
  { label: 'سوخاری', icon: 'assets/icons/categories/سوخاری.svg' },
  { label: 'سوشی', icon: 'assets/icons/categories/سوشی.svg' },
  {
    label: 'سوپ و استارترها',
    icon: 'assets/icons/categories/سوپ_و_استارتر_ها.svg',
  },
  { label: 'شیک', icon: 'assets/icons/categories/شیک.svg' },
  { label: 'صبحانه ایرانی', icon: 'assets/icons/categories/صبحانه_ایرانی.svg' },
  { label: 'صبحانه فرنگی', icon: 'assets/icons/categories/صبحانه_فرنگی.svg' },
  { label: 'غذای ایرانی', icon: 'assets/icons/categories/غذای_ایرانی.svg' },
  { label: 'غذای فرنگی', icon: 'assets/icons/categories/غذای_فرنگی.svg' },
  { label: 'قهوه سرد', icon: 'assets/icons/categories/قهوه_سرد.svg' },
  { label: 'قهوه گرم', icon: 'assets/icons/categories/قهوه_گرم.svg' },
  { label: 'ماکتل', icon: 'assets/icons/categories/ماکتل.svg' },
  {
    label: 'منوی وگان',
    icon: 'assets/icons/categories/منوی_غذای_وگان.svg',
  },
  { label: 'میان وعده', icon: 'assets/icons/categories/میان_وعده.svg' },
  { label: 'نوشیدنی', icon: 'assets/icons/categories/نوشیدنی.svg' },
  { label: 'نوشیدنی سرد', icon: 'assets/icons/categories/نوشیدنی_سرد.svg' },
  {
    label: 'نوشیدنی گازدار',
    icon: 'assets/icons/categories/نوشیدنی_گازدار.svg',
  },
  { label: 'نوشیدنی گرم', icon: 'assets/icons/categories/نوشیدنی_گرم.svg' },
  { label: 'پاستا', icon: 'assets/icons/categories/پاستا.svg' },
  { label: 'پروتئین بار', icon: 'assets/icons/categories/پروتئین_بار.svg' },
  { label: 'پیتزا', icon: 'assets/icons/categories/پیتزا.svg' },
  { label: 'پیش‌غذا', icon: 'assets/icons/categories/پیش_غذا.svg' },
  { label: 'چاباتا', icon: 'assets/icons/categories/چاباتا.svg' },
  { label: 'چای بار', icon: 'assets/icons/categories/چای_بار.svg' },
  { label: 'چلوخورشت', icon: 'assets/icons/categories/چلوخورشت.svg' },
  { label: 'کباب', icon: 'assets/icons/categories/کباب.svg' },
  { label: 'کته', icon: 'assets/icons/categories/کته.svg' },
  { label: 'کیک و دسر', icon: 'assets/icons/categories/کیک_و_دسر.svg' },
];
