version: "3.9"

services:

  jast.pwa.dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: jast-pwa:${TAG:-local}
    container_name: jast.pwa.dev
    hostname: jast.pwa
    restart: unless-stopped
    stop_grace_period: 5s
    profiles:
      - dev
    environment:
      TZ: "Asia/Tehran"
    labels:
      com.docker.service: "Jast PWA"
      com.jast.company: "Jast LLC [jast.fit]"
      com.jast.component: "The NGINX-1.22.1 Service"
      com.jast.description: "Jast Ingress [NGINX] For Serving Main PWA For Dev Enviroment"
      com.jast.os: "Debian Linux"
    expose:
      - 3000
    ports:
      - "${BIND_IP}:${BIND_PORT:-8081}:3000"
    networks:
      jast_pwa_net_frontend:

  jast.pwa.prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: jast-pwa:${TAG:-local}
    container_name: jast.pwa.prod
    hostname: jast.pwa
    restart: always
    stop_grace_period: 10s
    profiles:
      - prod
    environment:
      TZ: "Asia/Tehran"
    labels:
      com.docker.service: "Jast PWA"
      com.jast.company: "Jast LLC [jast.fit]"
      com.jast.component: "The NGINX-1.22.1 Service"
      com.jast.description: "Jast Ingress [NGINX] For Serving Main PWA For Prod Enviroment"
      com.jast.os: "Debian Linux"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./.docker/nginx.prod.conf:/etc/nginx/nginx.conf:ro"
    expose:
      - 80
    ports:
      - "${BIND_IP}:${BIND_PORT:-8081}:80"
    networks:
      jast_pwa_net_frontend:
    
networks:
  jast_pwa_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"